---
abstract: 'An object to help test SFTPs'
author:
  - 'Sawyer X <xsawyerx@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Term::ReadLine: 0
  Term::ReadPassword: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300002, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-SFTP
requires:
  Carp: 0
  English: 0
  Moose: 0
  Net::SFTP::Foreign: 0
  Test::Builder: 0
  Test::Builder::Module: 0
  namespace::autoclean: 0
  parent: 0
  strict: 0
  warnings: 0
resources:
  repository: git://github.com/xsawyerx/test-sftp.git
version: 1.10
